# NumPy

In [2]:
import numpy as np

In [11]:
### Create a 3x1 numpy array
a = np.array([1,2,3])

### Print object type
print(type(a))

### Print shape
print(a.shape)  # 1D obj with 3 values

### Print some values in a
print(a[0], a[1], a[2], sep=', ')

print(a[0], end='\n\n')
for value in a:
    print(value)

<class 'numpy.ndarray'>
(3,)
1, 2, 3
1

1
2
3


In [17]:
### Create a 2x2 numpy array
b = np.array([[1,2],[3,4]])
print(b, end='\n\n')
### Print shape
print(b.shape)
print(np.shape(b))
print(type(a.shape))

[[1 2]
 [3 4]]

(2, 2)
(2, 2)
<class 'tuple'>


In [23]:
## Print some values in b
print(b[0,0], b[0,1], b[1,1], end='\n\n')
for i in range(b.shape[0]):
    for j in range(b.shape[0]):
        print(b[i,j])

1 2 4

1
2
3
4


In [29]:
# Zeroes
z = np.zeros((3,2))
print(z)

ones = np.ones((4,3))
print(ones)

full = np.full((3, 3), 9)
print(full)

# full = np.full((3, 3), 0)
# print(full)
random = np.random.random((3, 4))
print(random)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[0.5916155  0.42890844 0.79845187 0.72787075]
 [0.15030885 0.68337834 0.51595973 0.36508021]
 [0.0056671  0.35599051 0.44233198 0.06942476]]


In [28]:
### Create a 3x2 numpy array
c = np.array([[1,2],[3,4],[5,6]])

### Print shape
print(c.shape)
print(c.ndim)
### Print some values in c
print(c[0,1], c[1,0], c[2,0], c[2,1])

(3, 2)
2
2 3 5 6


### Indexing

In [34]:
h = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(h)
h = h[:2, 0:3]
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [5 6 7]]


### Changing the slice results in changing an array

In [38]:
## Important!!!!
h = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
i = h[:2, 1:3]
print(h, i, sep='\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [39]:
i[0, 0] = 500
print(h)

[[  1 500   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


### Datatypes in NumPy

In [40]:
j = np.array([1, 2])
print(j.dtype)

k = np.array([1.0, 2.0])
print(k.dtype)

int32
float64


In [41]:
# Forcing the type:
l = np.array([1.0, 2.0], dtype=np.int64)
print(l, l.dtype, sep='\n')

[1 2]
int64


### Array math

In [56]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [55]:
print(x, end='\n\n')
# Compute sum of all elements; prints "10"
print(np.sum(x))

# Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=0))
# Compute sum of each row; prints "[3 7]"
print(np.sum(x, axis=1))

[[1. 2.]
 [3. 4.]]

10.0
[4. 6.]
[3. 7.]


In [57]:
x = np.array([[1,2],[3,4]])

### Compute mean of all elements; prints "2.5"
print(np.mean(x))

### Compute mean of each column; prints "[2 3]"
print(np.mean(x, axis=0)) 

### Compute mean of each row; prints "[1.5 3.5]"
print(np.mean(x, axis=1))

2.5
[2. 3.]
[1.5 3.5]
